### PR TITLE
Merge upstream/main into osgeo/grass#2684

### PR DESCRIPTION
**Pull request by echoix**
To update PR osgeo/grass#2684

### CODE REVIEW

**Comment by neteler** [comment]
Hi @echoix - the purpose of this PR is entirely unclear to me...

**Comment by echoix** [comment]
It is so "fix the merge conflicts", ie, merge main into the pr branch. I cannot add commits to the OSGeo/grass#2684 PR otherwise, as I'm not a maintainer.

Is it clearer with this?

**Comment by echoix** [comment]
If you want to redo it yourself, there is in fact only 12 files with conflicts that were really changed.

**Comment by neteler** [comment]
I have manually ported the clang-format changes into the CMake PR using `meld`, submitted in https://github.com/OSGeo/grass/pull/2684/commits/ea058ff3adb5158b270380f3dc7e716318f2a3e0 (`clang-format` itself didn't yield any effect, for whatever reason).

Now the CI is running again in https://github.com/OSGeo/grass/pull/2684.

**Comment by neteler** [comment]
May this PR in my fork be closed?

**Comment by neteler** [comment]
Closing since upstream https://github.com/OSGeo/grass/pull/2684 has been closed, continued in a separate PR (see there).

**Pull request closed without merging**
